Repository gardener/hyperkube, pull requests merged in 2024-03, with the labels that each got.

#15 Verify signatures of downloaded Kubernetes artifacts and bump versions
  .dockerignore
  Dockerfile
  KUBERNETES_VERSION
  MINIMUM_KUBERNETES_VERSION
  README.md
  scripts/get-k8s-binary.sh
Labels: reviewed/ok-to-test, reviewed/lgtm, size/s

#19 Seeting minimum k8s version to 1.26.15
  MINIMUM_KUBERNETES_VERSION
Labels: reviewed/lgtm, size/xs

#17 Make repo compliant
  .ci/check-and-release
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSE.md
  LICENSES/Apache-2.0.txt
  LICENSES/CC-BY-4.0.txt
  Makefile
  NOTICE.md
  README.md
Labels: reviewed/lgtm, size/xl, area/ipcei
